spring:
  profiles:
    active: prod
camel.springboot.shutdownTimeout: 2
---
spring:
  profiles: dev
  datasource:
      driver-class-name: org.postgresql.Driver
      url: jdbc:postgresql://localhost:5432/localDB
      username: postgres
      password: root

startRoute: timer:myTimer?period=10s
fromRoute: file:data/input?delete=true&readLock=none
toRoute1: file:data/output
toRoute2: jdbc:dataSource
toRoute3: file:data/output?fileName=success.txt

message: DEV Environment
---
spring:
  profiles: mock
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/localDB
    username: postgres
    password: root

startRoute: direct:input
fromRoute: file:data/input?delete=true&readLock=none
toRoute1: mock:output
toRoute2: jdbc:dataSource
toRoute3: file:data/output?fileName=success.txt

message: MOCK Environment
---
spring:
  profiles: stage
  datasource:
      driver-class-name: org.postgresql.Driver
      url: jdbc:postgresql://localhost:5432/localDB
      username: postgres
      password: root

startRoute: timer:myTimer?period=10s
fromRoute: file:data/input?delete=true&readLock=none
toRoute1: file:data/output
toRoute2: jdbc:dataSource
toRoute3: file:data/output?fileName=success.txt

message: STAGE Environment
---
spring:
  profiles: prod
  datasource:
      driver-class-name: org.postgresql.Driver
      url: jdbc:postgresql://localhost:5432/localDB
      username: postgres
      password: root

startRoute: timer:myTimer?period=10s
fromRoute: file:data/input?delete=true&readLock=none
toRoute1: file:data/output
toRoute2: jdbc:dataSource
toRoute3: file:data/output?fileName=success.txt

message: PROD Environment
---