spring:
  profiles:
    active: prod
camel.springboot.shutdownTimeout: 2
---
spring:
  profiles: dev

startRoute: timer:myTimer?period=10s
fromRoute: file:data/input?delete=true&readLock=none
toRoute1: file:data/output

message: DEV Environment
---
spring:
  profiles: stage

startRoute: timer:myTimer?period=10s
fromRoute: file:data/input?delete=true&readLock=none
toRoute1: file:data/output

message: STAGE Environment
---
spring:
  profiles: prod

startRoute: timer:myTimer?period=10s
fromRoute: file:data/input?delete=true&readLock=none
toRoute1: file:data/output

message: PROD Environment
---